import "dotenv/config";
import express from "express";
import { marcPaywall } from "marc-stellar-sdk";

const app = express();
const port = Number(process.env.PORT ?? 4510);
const payTo = process.env.PAY_TO ?? "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

app.use(express.json());

const mockPaywall = marcPaywall({
  payTo,
  price: "$0.01",
  network: "stellar:testnet",
  description: "Access the local mock seller agent",
  mimeType: "application/json",
  facilitatorUrl:
    process.env.X402_FACILITATOR_URL ?? "https://channels.openzeppelin.com/x402/testnet",
  facilitatorApiKey: process.env.X402_API_KEY,
});

app.get("/health", (_req, res) => {
  res.json({
    ok: true,
    service: "seller-mock",
    status: "healthy",
    port,
    payTo,
  });
});

app.get("/api/mock", mockPaywall, (_req, res) => {
  res.json({
    success: true,
    agent: "seller-mock",
    message: "Static mock seller response for local buyer integration tests.",
    deliverable: {
      format: "json",
      content: {
        summary: "This response was generated by the mock seller agent.",
        status: "ok",
      },
    },
    payment: {
      required: true,
      amount: "$0.01",
      asset: "USDC",
    },
  });
});

app.get("/", (_req, res) => {
  res.json({
    service: "seller-mock",
    endpoints: [
      "GET /health",
      "GET /api/mock",
    ],
  });
});

app.listen(port, () => {
  console.log(`[seller-mock] listening on http://localhost:${port}`);
  console.log(`[seller-mock] protected endpoint: http://localhost:${port}/api/mock`);
});
